import { App } from "@/types/app";

export const APPS: App[] = [
  {
    id: "galaxy-games",
    title: "Galaxy Games Hub",
    category: "Gaming",
    description: "An interactive gaming hub presenting multiple retro, physics-based, and strategy web and mobile mini-games.",
    fullDescription: "Galaxy Games is a complete gaming compilation platform developed by Plaxora. Contains high-performance retro arcade games, gravity-defying physics engines, and tactical strategy puzzles, designed to work smoothly on both Android smartphones and iPhones. Features global leaderboards, offline gameplay modes, and responsive controls.",
    downloads: "5,400+",
    rating: 4.9,
    developer: "Plaxora Gaming Labs",
    version: "v1.2.0",
    lastUpdated: "2026-06-25",
    platforms: ["Android", "iOS"],
    size: "68 MB",
    accent: "from-amber-500 to-rose-500",
    features: [
      "Offline game access for puzzles and physics challenges",
      "Real-time global high-score sync via websockets",
      "Native device performance optimization minimizing thermal throttling",
      "Zero pop-up advertisements or system tracking frameworks",
      "Pre-configured game controller mapping adapters",
    ],
    requirements: [
      "Android v9.0 or higher",
      "iOS v15.0 or higher",
      "At least 2GB of device RAM recommended",
    ],
    changelog: [
      {
        version: "v1.2.0",
        date: "2026-06-25",
        changes: [
          "Added two new strategy card mini-games",
          "Improved touch response latency on iOS devices",
          "Optimized game package storage requirements",
        ],
      },
      {
        version: "v1.0.0",
        date: "2026-02-14",
        changes: ["Initial store release containing 4 core arcade mini-games"],
      },
    ],
  },
  {
    id: "sendpay-wallet",
    title: "SendPay Digital Wallet",
    category: "Fintech",
    description: "Secure, lightning-fast digital wallet concept app supporting multi-currency conversions and offline transactions.",
    fullDescription: "A secure, modern concept for mobile banking and digital wallets. Engineered with local IndexedDB caches to support quick ledger lookups, automated monthly savings trackers, and biometric lock verification triggers. Includes a multi-currency conversion module supporting instant exchange rate estimates.",
    downloads: "12,200+",
    rating: 4.8,
    developer: "Plaxora Fintech Corp",
    version: "v2.1.0",
    lastUpdated: "2026-05-18",
    platforms: ["Android", "iOS", "macOS"],
    size: "34 MB",
    accent: "from-blue-600 to-cyan-400",
    features: [
      "Secured biometric access via local device fingerprint/FaceID hooks",
      "Real-time currency exchange tracker updating every 5 minutes",
      "Automated bill utility payment triggers configured in background",
      "Offline transaction records syncing immediately when connection returns",
      "Clean UI layouts following accessibility (WCAG) contrast requirements",
    ],
    requirements: [
      "Android v10.0 or higher",
      "iOS v16.0 or higher",
      "macOS Ventura or higher (for desktop compiler builds)",
    ],
    changelog: [
      {
        version: "v2.1.0",
        date: "2026-05-18",
        changes: [
          "Integrated local encrypted SQLite transaction caches",
          "Added desktop widget dashboard support for macOS",
          "Fixed session expiry redirects errors",
        ],
      },
      {
        version: "v1.0.0",
        date: "2026-01-05",
        changes: ["Initial concept release with core ledger grids and profile menus"],
      },
    ],
  },
  {
    id: "plexora-cli",
    title: "Plexora Developer CLI",
    category: "DevTools",
    description: "Terminal utility command line script that automates Tailwind component generation, Git workflows, and builds local templates.",
    fullDescription: "A developer productivity command-line interface (CLI) tool packaged as a Node.js executable script. Automates repetitive coding steps by generating pre-styled Tailwind elements, configuring prisma schema relational tables, setting up email configs, and standardizing git commit comments.",
    downloads: "3,100+",
    rating: 4.9,
    developer: "Plaxora Open Source",
    version: "v1.3.1",
    lastUpdated: "2026-07-02",
    platforms: ["Windows", "macOS", "Linux"],
    size: "12 MB",
    accent: "from-purple-600 to-fuchsia-400",
    features: [
      "Scaffolds responsive landing pages and dashboard shells via single command line",
      "Automates Git formatting with pre-configured hook commit messages",
      "Cross-platform execution on Windows PowerShell, Bash, and macOS Terminal",
      "Integrated lint checks and dev compiler checkers",
    ],
    requirements: [
      "Node.js v18.0 or higher",
      "npm, yarn, or pnpm globally configured",
    ],
    changelog: [
      {
        version: "v1.3.1",
        date: "2026-07-02",
        changes: [
          "Fixed path separator bugs on Windows PowerShell",
          "Added nextjs page router component template generation configs",
        ],
      },
      {
        version: "v1.0.0",
        date: "2026-03-20",
        changes: ["Initial open-source release with standard generator commands"],
      },
    ],
  },
  {
    id: "apex-inventory",
    title: "Apex Inventory Manager",
    category: "Utility",
    description: "Desktop utility tool that tracks stock quantities, logs supplier invoices, and exports monthly sales spreadsheets.",
    fullDescription: "A lightweight desktop administration tool designed for small to medium businesses. Tracks stock inventories, logs warehouse locations, organizes supplier contacts, and compiles PDF invoices. Built with offline data caching, allowing shops to process inventory checks without internet connections.",
    downloads: "2,400+",
    rating: 4.7,
    developer: "Plaxora Enterprise",
    version: "v1.0.2",
    lastUpdated: "2026-05-30",
    platforms: ["Windows", "macOS"],
    size: "52 MB",
    accent: "from-teal-600 to-emerald-500",
    features: [
      "Offline-first inventory lists using browser local IndexedDB sync",
      "Automatic supplier invoice PDF generation with customized invoice designs",
      "Monthly and weekly sales dashboard logs using area chart views",
      "Export capability generating CSV spreadsheets for accounting records",
    ],
    requirements: [
      "Windows 10/11 x64 architecture",
      "macOS Monterey or higher",
      "Minimum 100MB of free hard drive storage",
    ],
    changelog: [
      {
        version: "v1.0.2",
        date: "2026-05-30",
        changes: [
          "Added support for multi-location warehouse inventories",
          "Improved PDF generation styling template",
        ],
      },
      {
        version: "v1.0.0",
        date: "2026-02-10",
        changes: ["Initial release with basic invoice generation and item lists"],
      },
    ],
  },
];
