import { BlogPost } from "@/types/blog";

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "react-server-components-tutorial",
    title: "Mastering React Server Components in Next.js 16",
    excerpt: "Learn how to optimize database queries, minimize client bundle sizes, and use React Server Components for SEO-friendly performance.",
    content: `React Server Components (RSC) represent a paradigm shift in how we build React applications. In Next.js 16, they are the default building block, enabling developers to render UI on the server, fetch data right inside the component, and significantly reduce JavaScript payloads sent to the browser.\n\n### Why Server Components Matter\nTraditionally, React apps fetch data on the client using useEffect hooks, resulting in a waterfall request chain. With RSC, fetching is done directly on the server database layer. The client only downloads the pre-rendered HTML and a tiny interactive client script bundle.\n\n### Core Best Practices\n1. Keep Data Fetching on the Server: Query PostgreSQL tables or call external APIs directly in async server component functions.\n2. Pass Static Props: Avoid serializing complex database prototypes down to client children.\n3. Wrap Client Interactions Narrowly: Only mark elements containing useState/useEffect with the 'use client' directive. Keep parent containers server-rendered.\n\nBy splitting your layout logic, you can achieve 90+ Lighthouse speeds easily, securing higher SEO rankings and smoother mobile browsing.`,
    category: "Next.js",
    date: "2026-07-02",
    readTime: "5 min read",
    author: "Masud Parvez",
    authorRole: "Principal Software Engineer",
    accent: "from-blue-600 via-indigo-650 to-cyan-500",
  },
  {
    id: "vps-docker-deployment-guide",
    title: "Deploying Docker Containers on Cheap VPS Servers",
    excerpt: "A step-by-step tutorial configuring reverse proxies, automated SSL renewals, and custom Docker Compose files on Linux VPS.",
    content: `Hosting SaaS applications doesn't have to be expensive. By leveraging lightweight Docker containers, you can host PostgreSQL databases, Node.js APIs, and Next.js frontends on a cheap $5/month VPS (Virtual Private Server) with 100% control over server parameters.\n\n### Nginx and SSL Configuration\nTo route traffic to container ports, configure Nginx as a reverse proxy. Use Certbot to automate Let's Encrypt SSL key handshakes, ensuring HTTPS connections on your landing domains.\n\n### Sample Docker Compose Script\nConfigure separate containers for database and frontend layers in a single compose file. Map network bridges so frontend systems can access DB instances securely without exposing database ports to public public IPs.\n\n### Auto-Restart Rules\nAlways add the 'restart: unless-stopped' rule to compose containers. If the VPS reboots during server maintenance, Docker will automatically reboot your containers, preserving uptime SLAs.`,
    category: "DevOps",
    date: "2026-06-20",
    readTime: "7 min read",
    author: "Tahmid Reza",
    authorRole: "Cloud Devops Lead",
    accent: "from-teal-650 to-emerald-500",
  },
  {
    id: "bkash-nagad-api-integration",
    title: "bKash & Nagad Tokenized API Payment Integrations",
    excerpt: "Configure tokenized checkouts, secure query callback URLs, verify webhooks, and record transaction receipts in DB ledgers.",
    content: `Integrating tokenized checkout flows for bKash and Nagad requires a solid understanding of API key handshakes, verification query endpoints, and secure webhook setups. Here is a developer audit guide for merchants in Bangladesh.\n\n### Phase 1: Authentication Token Handshake\nCall bKash merchant authentication endpoints using APP_KEY and APP_SECRET headers to fetch a tokenized authorization string valid for 24 hours. Cache this token inside Redis to avoid calling the handshake on every checkout.\n\n### Phase 2: Checkout URL Generation\nInitialize payment objects with BDT prices, merchant invoice references, and callback URLs. Route the checkout redirect response to users. Once the user enters their PIN and OTP, bKash redirects back with an authorization query status.\n\n### Phase 3: Webhook Verification\nDo not rely on client-side redirects to confirm payments. Always verify the transaction status by calling payment query APIs server-to-server. Record transaction receipts on database tables only after querying successfully.`,
    category: "Fintech",
    date: "2026-07-08",
    readTime: "8 min read",
    author: "Masud Parvez",
    authorRole: "Principal Software Engineer",
    accent: "from-purple-600 via-pink-650 to-rose-500",
  },
  {
    id: "offline-first-pos-case",
    title: "Why Offline-First Architecture is Critical for Retail POS",
    excerpt: "How we configured IndexedDB and service workers to keep store checkouts active during Peak Eid seasons without internet.",
    content: `Point-of-Sale applications must remain active 24/7. When internet connections dropout during busy retail checkout hours, transactions fail, queues grow, and merchants lose sales. An offline-first architecture is the only reliable solution.\n\n### IndexedDB Storage Caching\nInstead of calling server APIs for stock lists, cache product codes on local IndexedDB browser databases. Search checks execute locally, rendering item lists instantly without latency.\n\n### Service Workers Synchronization\nRegister service worker threads in the browser background. When cashiers finalize a sale, log the transaction to a local pending table. Configure listener hooks to broadcast sync payloads to central servers the moment internet returns.\n\n### Conflict Resolution\nManage inventory conflict rules. If stock amounts update offline in two stores simultaneously, reconcile stock counts on central DB tables based on chronological timestamps.`,
    category: "Case Study",
    date: "2026-05-14",
    readTime: "6 min read",
    author: "Sultana Yasmin",
    authorRole: "Database Architect",
    accent: "from-amber-500 via-orange-550 to-rose-550",
  },
];
