import { JobListing } from "@/types/career";

export const JOB_LISTINGS: JobListing[] = [
  {
    id: "senior-nextjs-engineer",
    title: "Senior Next.js Full Stack Engineer",
    department: "Engineering",
    type: "Full-time",
    location: "Remote (Dhaka preferred)",
    salary: "৳60,000 – ৳90,000 / month",
    description: "We are seeking an experienced Next.js full-stack engineer to architect client-facing dashboards and payment-gated product delivery systems. You will own end-to-end feature delivery from database design to production deploys.",
    requirements: [
      "3+ years of Next.js App Router and React Server Components experience",
      "Proficiency with PostgreSQL, Prisma ORM, and Redis caching",
      "Hands-on experience with bKash or Nagad API payment integrations",
      "Understanding of CI/CD pipelines using GitHub Actions",
      "Strong TypeScript skills with strict mode configurations",
    ],
    perks: [
      "100% remote-first flexible working schedule",
      "Access to all Plaxora product licenses and templates",
      "Annual performance bonuses",
      "Open source contribution allowance",
    ],
    postedDate: "2026-07-10",
  },
  {
    id: "flutter-mobile-dev",
    title: "Flutter Mobile Developer",
    department: "Engineering",
    type: "Remote",
    location: "Anywhere (GMT+6 timezone)",
    salary: "৳45,000 – ৳70,000 / month",
    description: "Build and maintain native Android and iOS mobile applications using Flutter. You will integrate offline-first IndexedDB caches, biometric authentication login checks, and cross-platform payment UIs.",
    requirements: [
      "2+ years of Flutter/Dart development experience",
      "Experience with BLoC state management patterns",
      "Familiarity with Hive or SQLite local storage plugins",
      "Knowledge of Android Studio signing configurations",
      "Ability to write widget tests and integration test suites",
    ],
    perks: [
      "Hardware setup stipend (৳25,000 one-time)",
      "Conference and certification fee sponsorships",
      "Quarterly team virtual meetups",
    ],
    postedDate: "2026-07-01",
  },
  {
    id: "ui-ux-product-designer",
    title: "UI/UX Product Designer",
    department: "Design",
    type: "Contract",
    location: "Remote (Worldwide)",
    salary: "৳30,000 – ৳50,000 / month",
    description: "Design pixel-perfect UI mockups, component wireframes, and interactive Figma prototypes for Plaxora's SaaS dashboards and product landing pages. Collaborate directly with our lead engineers on design system guidelines.",
    requirements: [
      "Proficiency with Figma (auto-layout, components, variants)",
      "Understanding of accessibility WCAG 2.1 standards",
      "Strong portfolio demonstrating dashboard and landing page designs",
      "Experience creating and documenting design system tokens",
    ],
    perks: [
      "Project milestone bonuses",
      "Flexible hours with async reviews",
      "Creative tools budget (Figma, Adobe XD subscriptions)",
    ],
    postedDate: "2026-06-28",
  },
  {
    id: "devops-cloud-specialist",
    title: "DevOps & Cloud Specialist",
    department: "Operations",
    type: "Part-time",
    location: "Remote",
    salary: "৳35,000 – ৳55,000 / month",
    description: "Configure and maintain Dockerized VPS server environments, automated SSL renewals, Nginx routing proxies, and PostgreSQL backup strategies. Monitor uptime metrics and SLA compliance dashboards.",
    requirements: [
      "Hands-on experience with Docker and Docker Compose",
      "Linux server administration (Ubuntu 22 LTS)",
      "Nginx reverse proxy and Certbot SSL configuration",
      "Experience with monitoring tools (UptimeRobot, Grafana)",
    ],
    perks: [
      "Infrastructure credits allowance",
      "Competitive hourly contract rates",
      "Long-term retainer contracts available",
    ],
    postedDate: "2026-07-05",
  },
];
