import { Project } from "@/types/portfolio";

export const PORTFOLIO_PROJECTS: Project[] = [
  {
    id: "vortex-pos-case",
    title: "Point-of-Sale System for Retail Chain",
    client: "Rongdhonu Fashion Ltd",
    niche: "Retail Chain Enterprise",
    category: "Enterprise",
    description: "Refactored inventory databases and optimized checkouts for a 24-store clothing brand, handling 15,000+ daily transactions.",
    challenge: "The client was experiencing billing dropouts during Peak Eid seasons due to centralized database lockups. Cashiers could not access stock lists without active internet, causing long checkout queues.",
    solution: "We engineered Vortex POS, a custom offline-first Point-of-Sale terminal. We configured local IndexedDB browser caches to store stock entries locally. We built background service worker threads to synchronize transactions immediately once internet connectivity resumed, and implemented web socket channels to broadcast live stock levels across warehouse drawers.",
    results: [
      { label: "Checkout Speed", value: "+45% faster" },
      { label: "Offline Uptime", value: "100.0%" },
      { label: "Server CPU Load", value: "-60% drop" },
    ],
    techStack: ["Next.js", "Tailwind CSS", "IndexedDB", "WebSockets", "Prisma"],
    testimonial: {
      quote: "Plaxora completely revamped our checkouts. We processed our entire Eid sales offline without a single database crash.",
      author: "Ahmad Sharif",
      role: "Operations Director, Rongdhonu Fashion",
    },
    imageGradient: "from-blue-600 via-indigo-650 to-cyan-500",
  },
  {
    id: "medplus-emr-case",
    title: "MedPlus Clinical Electronic Medical Records",
    client: "MedPlus Medical Services Group",
    niche: "Healthcare Clinics Network",
    category: "Web Dev",
    description: "Secure HIPAA-compliant healthcare EHR database managing patient records, prescriptions, and slot bookings.",
    challenge: "MedPlus required a unified EHR to coordinate 5 clinics. The patient list was slow to load, search results took up to 6 seconds, and doctors complained about complex, confusing prescription input fields.",
    solution: "We designed a Next.js App Router clinic dashboard with server-side caching. We built a fast indexed elastic search engine that indexes patient names instantly. All medical data is encrypted on PostgreSQL tables, and biometric verification controls verify doctor session logs.",
    results: [
      { label: "Patient Query Speed", value: "0.2s instant" },
      { label: "Daily Appointments", value: "1,800+ booked" },
      { label: "HIPAA Security Score", value: "100/100" },
    ],
    techStack: ["React", "PostgreSQL API", "Redis Cache", "AES-256", "Next.js"],
    testimonial: {
      quote: "Our doctors can look up medical history in milliseconds. The custom prescription autocomplete layout saves hours of handwriting daily.",
      author: "Dr. Farhana Rahman",
      role: "Chief Medical Officer, MedPlus Clinic",
    },
    imageGradient: "from-teal-600 via-emerald-650 to-cyan-500",
  },
  {
    id: "sendpay-wallet-case",
    title: "SendPay Mobile Digital Wallet App",
    client: "SendPay Fintech Inc",
    niche: "Mobile Payments & Fintech",
    category: "Mobile Apps",
    description: "Sleek iOS and Android digital wallet with biometric verification, instant currency convertors, and SMS alert hooks.",
    challenge: "SendPay needed a mobile banking interface to attract younger demographics. The app had to boot in under 2 seconds, support instant local currency conversions, and authenticate transactions securely.",
    solution: "We built a native Flutter application with local SQLite databases. We integrated Android FingerprintManager and iOS FaceID hooks, and configured automated Twilio webhooks to dispatch transactional SMS receipts within 3 seconds of sending cash.",
    results: [
      { label: "App Boot Time", value: "1.4 Seconds" },
      { label: "Active App Users", value: "50,000+" },
      { label: "Transaction Latency", value: "< 1.2s avg" },
    ],
    techStack: ["Flutter", "Dart", "SQLite DB", "Twilio SMS", "Biometric API"],
    testimonial: {
      quote: "The interface is gorgeous and lightning-fast. Our transaction volume increased by 300% within two months of launch.",
      author: "Ziaul Huq",
      role: "Founder & CTO, SendPay Wallet",
    },
    imageGradient: "from-purple-600 via-pink-650 to-rose-500",
  },
  {
    id: "proptech-catalog-case",
    title: "Bespoke PropTech Dynamic Maps Portal",
    client: "BariChai Property Listings",
    niche: "Real Estate Listings",
    category: "UI/UX",
    description: "Advanced Figma design and frontend catalog mapping properties on interactive maps with geo-location pins.",
    challenge: "BariChai's users struggled to find rentals in specific sectors of Dhaka because standard listing grids failed to show actual block borders or nearby metro stations.",
    solution: "We drafted a high-fidelity Figma prototype and implemented custom SVG sector maps. We integrated map APIs to cluster real estate pins dynamically based on coordinates, and built multi-range slider filters that filter listings instantly.",
    results: [
      { label: "User Session Duration", value: "+180% increase" },
      { label: "Lead Contacts", value: "+40% conversion" },
      { label: "Map Cluster Loading", value: "0.15s dynamic" },
    ],
    techStack: ["Figma Design", "React Maps", "GeoJSON Vectors", "Tailwind CSS"],
    testimonial: {
      quote: "The sector maps are intuitive. Clients can find apartments near school sectors without typing complex searches.",
      author: "Munirul Haque",
      role: "CEO, BariChai Real Estate",
    },
    imageGradient: "from-amber-500 via-orange-550 to-rose-550",
  },
];
