import { Product } from "@/types/product";

export const PRODUCTS: Product[] = [
  {
    id: "plaxora-ecommerce-template",
    title: "Plaxora-Shop eCommerce Template",
    category: "Next.js",
    description: "Ultra-fast eCommerce frontend with complete cart, search filters, manual payment forms, and Next.js ISR pre-rendering.",
    fullDescription: "A complete, high-converting digital storefront template engineered using Next.js 16 (App Router) and Tailwind CSS v4. It features a fully responsive product grid, comprehensive sidebar search filters, a state-managed shopping cart, and a dedicated checkout page supporting manual bKash/Nagad transactions. Designed specifically for digital agencies, software template sellers, and retail stores aiming for near-instant page load speeds.",
    price: "1,500 BDT",
    priceVal: 1500,
    originalPrice: "3,000 BDT",
    tags: ["Next.js", "TailwindCSS", "Prisma", "eCommerce"],
    rating: 4.9,
    downloads: "284",
    imageGradient: "from-indigo-600 via-purple-600 to-pink-500",
    demoLink: "https://demo.plaxora.shop",
    features: [
      "Optimized Next.js App Router structure with Turbopack support",
      "Dynamic Incremental Static Regeneration (ISR) for instant loads",
      "Interactive local cart state managed via Zustand",
      "Integrated manual payment checkout form supporting bKash, Nagad, and Rocket",
      "Custom responsive dashboard layout for order status checks",
      "Pre-configured dark-mode aesthetics using next-themes",
      "Search Engine Optimization (SEO) structured meta tags and Sitemap generators",
    ],
    requirements: [
      "Node.js v20.x or higher",
      "npm, yarn, or pnpm package manager",
      "PostgreSQL or SQLite (optional database log database)",
    ],
    changelog: [
      {
        version: "v1.1.0",
        date: "2026-06-15",
        changes: [
          "Upgraded package dependencies to Tailwind CSS v4",
          "Improved manual payment form client-side validations",
          "Fixed local storage hydration errors in cart store",
        ],
      },
      {
        version: "v1.0.0",
        date: "2026-03-01",
        changes: ["Initial codebase release with next-auth, prisma, and standard cart layouts"],
      },
    ],
  },
  {
    id: "sass-dashboard-boilerplate",
    title: "Vortex SaaS Admin Boilerplate",
    category: "React",
    description: "Clean dashboard framework featuring charts, notifications, multi-role user dashboards, and Stripe hook adapters.",
    fullDescription: "An administrative SaaS framework dashboard setup with complete design tokens, interactive sidebar layouts, charts widgets, notifications dropdown, and customizable theme panels. Comes integrated with user authorization triggers, active session checking, and Stripe subscription webhook endpoints.",
    price: "2,200 BDT",
    priceVal: 2200,
    originalPrice: "4,500 BDT",
    tags: ["React", "Recharts", "Zustand", "SaaS"],
    rating: 4.8,
    downloads: "192",
    imageGradient: "from-blue-600 via-cyan-500 to-indigo-500",
    demoLink: "https://vortex.plaxora.shop",
    features: [
      "Responsive Sidebar & Grid Dashboard layouts",
      "Clean chart visualizations powered by Recharts",
      "Global store for notifications and dark mode themes using Zustand",
      "Prebuilt user management grid and role-based permissions views",
      "JWT decoder wrappers and Axios client instance setup",
    ],
    requirements: [
      "React v19 or higher",
      "Modern browser with JavaScript enabled",
      "Node.js developer environment",
    ],
    changelog: [
      {
        version: "v1.0.2",
        date: "2026-05-10",
        changes: ["Added Recharts area charts animations", "Refactored JWT verification logic"],
      },
      {
        version: "v1.0.0",
        date: "2026-01-20",
        changes: ["Initial dashboard release with dark mode styling and tabular grids"],
      },
    ],
  },
  {
    id: "figma-ui-kit-pro",
    title: "Plaxora Premium UI Figma Kit",
    category: "Figma",
    description: "Design system containing 200+ responsive elements, dark-first grids, custom web layouts, and interactive variables.",
    fullDescription: "A comprehensive Figma design library constructed using the latest Figma auto-layout, variables, and component features. Ideal for UI designers, developers, and product owners seeking to wireframe SaaS dashboards, mobile apps, or portfolio layouts without starting from a blank canvas. Styled with dark-first neon cyan and purple accents.",
    price: "850 BDT",
    priceVal: 850,
    originalPrice: "1,800 BDT",
    tags: ["Figma", "UI/UX", "Design Tokens", "Wireframing"],
    rating: 4.9,
    downloads: "421",
    imageGradient: "from-teal-600 via-cyan-600 to-emerald-500",
    demoLink: "#",
    features: [
      "200+ responsive components (buttons, inputs, tables, cards)",
      "Dark-first color schemes utilizing dynamic design variables",
      "Prebuilt UI layouts for landing pages, admin panels, and user settings",
      "Auto-layout 5.0 configured for seamless drag-and-resize testing",
      "Lifetime updates and instant design file download accesses",
    ],
    requirements: [
      "Active Figma free or professional account",
      "Basic understanding of Figma Components & Styles",
    ],
    changelog: [
      {
        version: "v2.0.0",
        date: "2026-07-01",
        changes: ["Upgraded components to utilize Figma Variables", "Added 50 new mobile layout panels"],
      },
    ],
  },
  {
    id: "flutter-wallet-app",
    title: "Vivid Fintech App Template",
    category: "Flutter",
    description: "Multi-platform mobile fintech app shell featuring offline-sync SQLite DB, biometrics support, and chart animations.",
    fullDescription: "A cross-platform Flutter application starter tailored for fintech startups. It provides prebuilt views for transactions, wallets, analytics charts, user profile setups, and settings. Engineered with BloC state management patterns, local secure storage caching, SQLite sync logs, and native biometric lock (FaceID/Fingerprint) adapters.",
    price: "3,200 BDT",
    priceVal: 3200,
    originalPrice: "6,000 BDT",
    tags: ["Flutter", "Dart", "BLoC", "SQLite"],
    rating: 4.9,
    downloads: "135",
    imageGradient: "from-purple-600 to-fuchsia-400",
    demoLink: "#",
    features: [
      "Single consolidated Dart codebase deploying to iOS, Android, and macOS",
      "State management structure configured using flutter_bloc",
      "Local relational database caching with SQLite and encrypted secure storage",
      "Biometric authorization hooks (local_auth wrapper)",
      "Stunning transaction and balance charts using fl_chart",
    ],
    requirements: [
      "Flutter SDK v3.22.x or higher",
      "Android Studio / Xcode for compiling builds",
      "Visual Studio Code or IntelliJ IDEA editor",
    ],
    changelog: [
      {
        version: "v1.0.0",
        date: "2026-04-12",
        changes: ["Initial Vivid Fintech release with transaction analytics and biometrics integration"],
      },
    ],
  },
  {
    id: "wordpress-agency-theme",
    title: "Plaxora Elementor WordPress Theme",
    category: "Scripts",
    description: "Responsive agency theme with custom Elementor widgets, Gutenberg blocks, and manual checkout extensions.",
    fullDescription: "An optimized Elementor Pro WordPress theme built for agencies, software developers, and product creators. It contains prebuilt homepage structures, portfolio archives, blog pages, and custom payment plugin attachments allowing Bkash/Nagad entries directly from WooCommerce checkout forms.",
    price: "1,200 BDT",
    priceVal: 1200,
    originalPrice: "2,500 BDT",
    tags: ["WordPress", "Elementor", "PHP", "WooCommerce"],
    rating: 4.7,
    downloads: "98",
    imageGradient: "from-orange-600 to-amber-500",
    demoLink: "#",
    features: [
      "Complete WooCommerce setup with custom manual checkout field extensions",
      "Drag-and-drop Elementor widget extensions pre-coded",
      "Optimized load times with minimal JS dependencies",
      "One-click theme demo import configurations",
      "SEO schemas and XML sitemaps compatibility built-in",
    ],
    requirements: [
      "WordPress v6.4 or higher",
      "PHP v8.1 or higher",
      "Elementor Pro (recommended for full template editing)",
    ],
    changelog: [
      {
        version: "v1.0.1",
        date: "2026-05-22",
        changes: ["Fixed manual checkout script compatibility with PHP 8.2", "Updated elementor widget packages"],
      },
    ],
  },
  {
    id: "plexora-cli",
    title: "Plexora Developer CLI tool",
    category: "Scripts",
    description: "Terminal utility command line script that automates nextjs component generation, prisma configurations, and git commits.",
    fullDescription: "A developer productivity command-line interface (CLI) tool packaged as a Node.js executable script. Automates repetitive coding steps by generating pre-styled Tailwind elements, configuring prisma schema relational tables, setting up email configs, and standardizing git commit comments.",
    price: "600 BDT",
    priceVal: 600,
    originalPrice: "1,500 BDT",
    tags: ["NodeJS", "CLI", "Shell Script", "Automation"],
    rating: 4.9,
    downloads: "512",
    imageGradient: "from-cyan-600 to-indigo-600",
    demoLink: "#",
    features: [
      "Interactive shell commands with prompt selection grids",
      "Template generation command producing files matching project layout conventions",
      "Auto-linting and compile checking triggers integrated",
      "Cross-platform execution on Windows PowerShell, Bash, and macOS Terminal",
    ],
    requirements: [
      "Node.js v18.x or higher",
      "npm package manager globally configured",
    ],
    changelog: [
      {
        version: "v1.2.0",
        date: "2026-06-30",
        changes: ["Added automatic tailwind component scaffolding", "Updated interactive prompt design"],
      },
    ],
  },
];
